In [17]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

load dataset

In [18]:
from google.collab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:



data = pd.read_csv('/content/drive/MyDrive/IMDB Dataset.csv')

In [20]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [21]:
data.shape

(50000, 2)

In [22]:
data["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

One hot Encoding

In [23]:
data.replace({"sentiment" : {"positive" : 1, "negative" : 0}}, inplace=True)

Data Preprocessing

In [24]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.9)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [25]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [26]:
train_data , test_data = train_test_split(data, test_size=0.2, random_state=42)

In [27]:
train_data.shape

(40000, 2)

In [28]:
test_data.shape

(10000, 2)

In [29]:
tokenizer = Tokenizer(num_words = 5000)
tokenizer.fit_on_texts(test_data["review"])

In [30]:
x_train = pad_sequences(tokenizer.texts_to_sequences(train_data["review"]), maxlen=200)
x_test = pad_sequences(tokenizer.texts_to_sequences(test_data["review"]), maxlen=200)

In [31]:
x_train

array([[ 776, 2301,    1, ...,  210,  374, 4301],
       [  14,    3, 1495, ...,   89,  104,    9],
       [   0,    0,    0, ...,    2,  734,   65],
       ...,
       [   0,    0,    0, ..., 1491,    2,  603],
       [   0,    0,    0, ...,  235,  104,  124],
       [   0,    0,    0, ...,   68,   71, 2087]], dtype=int32)

In [32]:
x_test

array([[   0,    0,    0, ..., 1050,  746,  162],
       [  12,  159,   58, ...,  397,    7,    7],
       [   0,    0,    0, ...,   51, 1081,   99],
       ...,
       [   0,    0,    0, ...,  124,  198, 3295],
       [   0,    0,    0, ..., 1080,    1, 2473],
       [   0,    0,    0, ...,    1,  341,   28]], dtype=int32)

In [45]:
y_train = train_data["sentiment"]
y_test =  test_data["sentiment"]

In [34]:
y_train

39087    0
30893    0
45278    1
16398    0
13653    0
        ..
11284    1
44732    1
38158    0
860      1
15795    1
Name: sentiment, Length: 40000, dtype: int64

In [35]:
y_test

39087    0
30893    0
45278    1
16398    0
13653    0
        ..
11284    1
44732    1
38158    0
860      1
15795    1
Name: sentiment, Length: 40000, dtype: int64

Model Building

In [36]:
model = Sequential()
model.add(Embedding(input_dim = 5000,output_dim =  128, input_length=200))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

In [37]:
model.summary

In [39]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [40]:
model.fit(x_train, y_train, epochs=5, batch_size=64, validation_split= 0.2)

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 216s 414ms/step - accuracy: 0.7086 - loss: 0.5468 - val_accuracy: 0.8420 - val_loss: 0.3709
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 205s 411ms/step - accuracy: 0.8562 - loss: 0.3521 - val_accuracy: 0.7269 - val_loss: 0.5333
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 206s 413ms/step - accuracy: 0.8207 - loss: 0.3993 - val_accuracy: 0.8737 - val_loss: 0.3146
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 206s 411ms/step - accuracy: 0.8887 - loss: 0.2728 - val_accuracy: 0.8788 - val_loss: 0.2957
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 207s 414ms/step - accuracy: 0.9089 - loss: 0.2273 - val_accuracy: 0.8824 - val_loss: 0.2919

In [46]:
loss,accuracy = model.evaluate(x_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 42s 132ms/step - accuracy: 0.8876 - loss: 0.2777

In [47]:
print(loss)
print(accuracy)

0.27654948830604553
0.8870999813079834

Building Predicting System

In [48]:
def Predictive_system(review):
  sequence = tokenizer.texts_to_sequences([review])
  padded_sequence = pad_sequences(sequence, maxlen=200)
  prediction = model.predict(padded_sequence)
  sentiment = "positive" if prediction > 0.5 else "negative"
  return sentiment

In [49]:
Predictive_system("this movie shit and amazing")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 421ms/step

'positive'

In [50]:
Predictive_system("this movie is not worth it")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

'negative'

In [51]:
Predictive_system("movie is suck")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

'negative'

In [52]:
Predictive_system("this movie shit and stunning")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

'positive'

saving model

In [57]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [55]:
import joblib
joblib.dump(tokenizer, "tokenizer.pkl")

['tokenizer.pkl']